#!/bin/sh /etc/rc.common

START=99
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

APP=weatherStation

start(){
        sleep 5
        service_start /usr/bin/$APP -1 weather -2 none -s 300
}

stop() {
        service_stop /usr/bin/$APP
}
