#!/bin/sh /etc/rc.common

START=99
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

APP=weatherStationExtended

start(){
        sleep 5
        service_start /usr/bin/$APP -1 thermo3 -i AwaLWM2M -s 5
}

stop() {
        service_stop /usr/bin/$APP
}
